import type { Metadata } from 'next'
import { Outfit, Noto_Serif } from 'next/font/google'
import './globals.css'

const bodyFont = Outfit({
  variable: '--font-outfit',
  subsets: ['latin']
})

const titleFont = Noto_Serif({
  variable: '--font-noto-serif',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${bodyFont.variable} ${titleFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
