import type { Metadata } from 'next';
import { Noto_Serif, Outfit, Sacramento } from 'next/font/google';

import './globals.css';

const bodyFont = Outfit({
    variable: '--font-body',
    subsets: ['latin'],
});

const titleFont = Noto_Serif({
    variable: '--font-serif',
    subsets: ['latin'],
});

const cursiveFont = Sacramento({
    variable: '--font-cursive',
    weight: '400',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${bodyFont.variable} ${titleFont.variable} ${cursiveFont.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
